steps:
- name: ubuntu
- name: 'gcr.io/poc-dna-automation-693335/bigquery-git'
  args:
    - '-m'
    - 'rsync'
    - '-d'
    - '-r'
    - './dags'
  
- name: 'gcr.io/poc-dna-automation-693335/bigquery-git'
  args:
    - '-m'
    - 'rsync'
    - '-d'
    - '-r'
    - 'plugins'
    - 'gs://demo12trial/'
#Logging
options:
  logging: CLOUD_LOGGING_ONLY
#completed
